/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package roadaccident;

import java.awt.Color;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author Noman
 */
public class S_Info_Time extends javax.swing.JFrame {

    /**
     * Creates new form S_Info_Time
     */
    public S_Info_Time() {
        initComponents();
        setTitle("Black Spots of Bangladesh");
          // getContentPane().setBackground(new Color(0,191,255));
          getContentPane().setBackground(new Color(255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_morning = new javax.swing.JButton();
        bt_noon = new javax.swing.JButton();
        bt_afternoon = new javax.swing.JButton();
        bt_evening = new javax.swing.JButton();
        bt_night = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        bt_morning.setBackground(new java.awt.Color(0, 204, 255));
        bt_morning.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        bt_morning.setForeground(new java.awt.Color(0, 153, 153));
        bt_morning.setText("Morning");
        bt_morning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_morningActionPerformed(evt);
            }
        });

        bt_noon.setBackground(new java.awt.Color(0, 153, 153));
        bt_noon.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        bt_noon.setForeground(new java.awt.Color(102, 102, 255));
        bt_noon.setText("Noon");
        bt_noon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_noonActionPerformed(evt);
            }
        });

        bt_afternoon.setBackground(new java.awt.Color(255, 255, 51));
        bt_afternoon.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        bt_afternoon.setForeground(new java.awt.Color(0, 0, 255));
        bt_afternoon.setText("Afternoon");
        bt_afternoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_afternoonActionPerformed(evt);
            }
        });

        bt_evening.setBackground(new java.awt.Color(0, 255, 204));
        bt_evening.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        bt_evening.setForeground(new java.awt.Color(0, 153, 204));
        bt_evening.setText("Evening");
        bt_evening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eveningActionPerformed(evt);
            }
        });

        bt_night.setBackground(new java.awt.Color(0, 255, 0));
        bt_night.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        bt_night.setForeground(new java.awt.Color(153, 153, 255));
        bt_night.setText("Night");
        bt_night.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nightActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_night, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_afternoon, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_morning, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bt_evening, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                    .addComponent(bt_noon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_noon, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_morning, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_afternoon, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_evening, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(bt_night, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_morningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_morningActionPerformed
        // TODO add your handling code here:
         setVisible(true);
        S_Info_Time_Morning t=new S_Info_Time_Morning("Road Accident in Morning", "Road Accident in Morning");
        t.pack();
       //setDefaultCloseOperation(ApplicationFrame.DISPOSE_ON_CLOSE);
       RefineryUtilities.centerFrameOnScreen(t);
         t.setVisible(true);
    }//GEN-LAST:event_bt_morningActionPerformed

    private void bt_noonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_noonActionPerformed
        // TODO add your handling code here:
         setVisible(true);
        S_Info_Time_Noon t=new S_Info_Time_Noon("Road Accident in Noon", "Road Accident in Morning");
        t.pack();
       //setDefaultCloseOperation(ApplicationFrame.DISPOSE_ON_CLOSE);
       RefineryUtilities.centerFrameOnScreen(t);
         t.setVisible(true);
    }//GEN-LAST:event_bt_noonActionPerformed

    private void bt_afternoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_afternoonActionPerformed
        // TODO add your handling code here:
         setVisible(true);
        S_Info_Time_Afternoon t=new S_Info_Time_Afternoon("Road Accident in Afternoon", "Road Accident in Morning");
        t.pack();
       //setDefaultCloseOperation(ApplicationFrame.DISPOSE_ON_CLOSE);
       RefineryUtilities.centerFrameOnScreen(t);
         t.setVisible(true);
    }//GEN-LAST:event_bt_afternoonActionPerformed

    private void bt_eveningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eveningActionPerformed
        // TODO add your handling code here:
          setVisible(true);
        S_Info_Time_Evening t=new S_Info_Time_Evening("Road Accident in Evening", "Road Accident in Morning");
        t.pack();
       //setDefaultCloseOperation(ApplicationFrame.DISPOSE_ON_CLOSE);
       RefineryUtilities.centerFrameOnScreen(t);
         t.setVisible(true);
        
    }//GEN-LAST:event_bt_eveningActionPerformed

    private void bt_nightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nightActionPerformed
        // TODO add your handling code here:
        setVisible(true);
        S_Info_Time_Night t=new S_Info_Time_Night("Road Accident in Night", "Road Accident in Morning");
        t.pack();
       //setDefaultCloseOperation(ApplicationFrame.DISPOSE_ON_CLOSE);
        RefineryUtilities.centerFrameOnScreen(t);
        t.setVisible(true);
        
        
    }//GEN-LAST:event_bt_nightActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        S_info s=new S_info();
        s.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_Info_Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_Info_Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_Info_Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_Info_Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S_Info_Time().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_afternoon;
    private javax.swing.JButton bt_evening;
    private javax.swing.JButton bt_morning;
    private javax.swing.JButton bt_night;
    private javax.swing.JButton bt_noon;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
